### ISSUE TITLE
refactor: use threadpool

### ISSUE THREAD

**Issue by kaushalmall** [kaushalmall/aem-hotfix-installer#16]
@badvision looking for details from you on this one.

**Comment by badvision** [comment]
ThreadPoolExecutor should be created with a min and max size of 1.  Using the execute method you can schedule work to be processed in order.   This is ideal compared to other alternatives because you can pause or abort scheduled work more easily on an executor than if you were rolling your own thread.  Also, the executor stats can be used to generate progress statistics as well.

**Comment by badvision** [comment]
Also make sure your source and target version are 1.8 so that your IDE can offer refactoring and suggestions to make the most use from method references and lambda expressions.

**Comment by kaushalmall** [comment]
@badvision look at this https://github.com/kaushalmall/aem-hotfix-installer/pull/20. Let me if this looks OK to merge

**Comment by badvision** [comment]
Should we close this issue now?

**Comment by kaushalmall** [comment]
yeah. It's done. Closing it
